version: '3.8'
services:

  frontend:
    image: vitaliiluki/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  db_postgres:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: vitaliiluki/foodgram_backend
    restart: always
    volumes:
      - foodgram_static_value:/backend/static/
      - foodgram_media_value:/backend/media/
    depends_on:
      - db_postgres
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static_value:/var/html/static/
      - foodgram_media_value:/var/html/media/
    depends_on:
      - frontend
      - web

volumes:
  foodgram_db_value:
  foodgram_static_value:
  foodgram_media_value:
    
