# Generated by Django 4.1.7 on 2023-03-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientrecipe_ingredient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipefavourite',
            old_name='favourite_id',
            new_name='favourite',
        ),
        migrations.RenameField(
            model_name='recipefavourite',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipeshoppingcart',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipeshoppingcart',
            old_name='shopping_cart_id',
            new_name='shopping_cart',
        ),
        migrations.RenameField(
            model_name='tagrecipe',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='tagrecipe',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
